version: 1.0.{build}
install:
  - cinst pester -y
  - cinst codecov -y

build: false

test_script:
    - ps: |
        Import-Module .\POSHPasswords.psd1 -verbose
        $testResultsFile = ".\TestsResults.xml"
        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -CodeCoverage @((gci .\cmdlets\*.ps1 -Recurse).FullName) -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }
   - codecov -f $testResultsFile -t "92c741d1-ef02-4590-8fa7-05e86666ab5a"
